--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- https://github.com/Roffild/qlua
--

local roffild_win1251 = {}

function roffild_win1251.getParamExAll()
    return {
        STATUS = {type = "STRING", desc = "Статус"},
        LOTSIZE = {type = "NUMERIC", desc = "Размер лота"},
        BID = {type = "NUMERIC", desc = "Лучшая цена спроса"},
        BIDDEPTH = {type = "NUMERIC", desc = "Спрос по лучшей цене"},
        BIDDEPTHT = {type = "NUMERIC", desc = "Суммарный спрос"},
        NUMBIDS = {type = "NUMERIC", desc = "Количество заявок на покупку"},
        OFFER = {type = "NUMERIC", desc = "Лучшая цена предложения"},
        OFFERDEPTH = {type = "NUMERIC", desc = "Предложение по лучшей цене"},
        OFFERDEPTHT = {type = "NUMERIC", desc = "Суммарное предложение"},
        NUMOFFERS = {type = "NUMERIC", desc = "Количество заявок на продажу"},
        OPEN = {type = "NUMERIC", desc = "Цена открытия"},
        HIGH = {type = "NUMERIC", desc = "Максимальная цена сделки"},
        LOW = {type = "NUMERIC", desc = "Минимальная цена сделки"},
        LAST = {type = "NUMERIC", desc = "Цена последней сделки"},
        CHANGE = {type = "NUMERIC", desc = "Разница цены последней к предыдущей сессии"},
        QTY = {type = "NUMERIC", desc = "Количество инструментов в последней сделке"},
        TIME = {type = "STRING", desc = "Время последней сделки"},
        VOLTODAY = {type = "NUMERIC", desc = "Количество инструментов в обезличенных сделках"},
        VALTODAY = {type = "NUMERIC", desc = "Оборот в деньгах"},
        TRADINGSTATUS = {type = "STRING", desc = "Состояние сессии"},
        VALUE = {type = "NUMERIC", desc = "Оборот в деньгах последней сделки"},
        WAPRICE = {type = "NUMERIC", desc = "Средневзвешенная цена"},
        HIGHBID = {type = "NUMERIC", desc = "Лучшая цена спроса сегодня"},
        LOWOFFER = {type = "NUMERIC", desc = "Лучшая цена предложения сегодня"},
        NUMTRADES = {type = "NUMERIC", desc = "Количество сделок за сегодня"},
        PREVPRICE = {type = "NUMERIC", desc = "Цена закрытия"},
        PREVWAPRICE = {type = "NUMERIC", desc = "Предыдущая оценка"},
        CLOSEPRICE = {type = "NUMERIC", desc = "Цена периода закрытия"},
        LASTCHANGE = {type = "NUMERIC", desc = "% изменения от закрытия"},
        PRIMARYDIST = {type = "STRING", desc = "Размещение"},
        ACCRUEDINT = {type = "NUMERIC", desc = "Накопленный купонный доход"},
        YIELD = {type = "NUMERIC", desc = "Доходность последней сделки"},
        COUPONVALUE = {type = "NUMERIC", desc = "Размер купона"},
        YIELDATPREVWAPRI = {type = "NUMERIC", desc = "Доходность по предыдущей оценке"},
        YIELDATWAPRICE = {type = "NUMERIC", desc = "Доходность по оценке"},
        PRICEMINUSPREVWAPRICE = {type = "NUMERIC", desc = "Разница цены последней к предыдущей оценке"},
        CLOSEYIELD = {type = "NUMERIC", desc = "Доходность закрытия"},
        CURRENTVALUE = {type = "NUMERIC", desc = "Текущее значение индексов Московской Биржи"},
        LASTVALUE = {type = "NUMERIC", desc = "Значение индексов Московской Биржи на закрытие предыдущего дня"},
        LASTTOPREVSTLPRC = {type = "NUMERIC", desc = "Разница цены последней к предыдущей сессии"},
        PREVSETTLEPRICE = {type = "NUMERIC", desc = "Предыдущая расчетная цена"},
        PRICEMVTLIMIT = {type = "NUMERIC", desc = "Лимит изменения цены"},
        PRICEMVTLIMITT1 = {type = "NUMERIC", desc = "Лимит изменения цены T1"},
        MAXOUTVOLUME = {type = "NUMERIC", desc = "Лимит объема активных заявок (в контрактах)"},
        PRICEMAX = {type = "NUMERIC", desc = "Максимально возможная цена"},
        PRICEMIN = {type = "NUMERIC", desc = "Минимально возможная цена"},
        NEGVALTODAY = {type = "NUMERIC", desc = "Оборот внесистемных в деньгах"},
        NEGNUMTRADES = {type = "NUMERIC", desc = "Количество внесистемных сделок за сегодня"},
        NUMCONTRACTS = {type = "NUMERIC", desc = "Количество открытых позиций"},
        CLOSETIME = {type = "STRING", desc = "Время закрытия предыдущих торгов (для индексов РТС)"},
        OPENVAL = {type = "NUMERIC", desc = "Значение индекса РТС на момент открытия торгов"},
        CHNGOPEN = {type = "NUMERIC", desc = "Изменение текущего индекса РТС по сравнению со значением открытия"},
        CHNGCLOSE = {type = "NUMERIC", desc = "Изменение текущего индекса РТС по сравнению со значением закрытия"},
        BUYDEPO = {type = "NUMERIC", desc = "Гарантийное обеспечение продавца"},
        SELLDEPO = {type = "NUMERIC", desc = "Гарантийное обеспечение покупателя"},
        CHANGETIME = {type = "STRING", desc = "Время последнего изменения"},
        SELLPROFIT = {type = "NUMERIC", desc = "Доходность продажи"},
        BUYPROFIT = {type = "NUMERIC", desc = "Доходность покупки"},
        TRADECHANGE = {type = "NUMERIC", desc = "Разница цены последней к предыдущей сделки (FORTS, ФБ СПБ, СПВБ)"},
        FACEVALUE = {type = "NUMERIC", desc = "Номинал (для инструментов СПВБ)"},
        MARKETPRICE = {type = "NUMERIC", desc = "Рыночная цена вчера"},
        MARKETPRICETODAY = {type = "NUMERIC", desc = "Рыночная цена"},
        NEXTCOUPON = {type = "NUMERIC", desc = "Дата выплаты купона"},
        BUYBACKPRICE = {type = "NUMERIC", desc = "Цена оферты"},
        BUYBACKDATE = {type = "NUMERIC", desc = "Дата оферты"},
        ISSUESIZE = {type = "NUMERIC", desc = "Объем обращения"},
        PREVDATE = {type = "NUMERIC", desc = "Дата предыдущего торгового дня"},
        DURATION = {type = "NUMERIC", desc = "Дюрация"},
        LOPENPRICE = {type = "NUMERIC", desc = "Официальная цена открытия"},
        LCURRENTPRICE = {type = "NUMERIC", desc = "Официальная текущая цена"},
        LCLOSEPRICE = {type = "NUMERIC", desc = "Официальная цена закрытия"},
        QUOTEBASIS = {type = "STRING", desc = "Тип цены"},
        PREVADMITTEDQUOT = {type = "NUMERIC", desc = "Признаваемая котировка предыдущего дня"},
        LASTBID = {type = "NUMERIC", desc = "Лучшая спрос на момент завершения периода торгов"},
        LASTOFFER = {type = "NUMERIC", desc = "Лучшее предложение на момент завершения торгов"},
        PREVLEGALCLOSEPR = {type = "NUMERIC", desc = "Цена закрытия предыдущего дня"},
        COUPONPERIOD = {type = "NUMERIC", desc = "Длительность купона"},
        MARKETPRICE2 = {type = "NUMERIC", desc = "Рыночная цена 2"},
        ADMITTEDQUOTE = {type = "NUMERIC", desc = "Признаваемая котировка"},
        BGOP = {type = "NUMERIC", desc = "БГО по покрытым позициям"},
        BGONP = {type = "NUMERIC", desc = "БГО по непокрытым позициям"},
        STRIKE = {type = "NUMERIC", desc = "Цена страйк"},
        STEPPRICET = {type = "NUMERIC", desc = "Стоимость шага цены"},
        STEPPRICE = {type = "NUMERIC", desc = "Стоимость шага цены (для новых контрактов FORTS)"},
        SETTLEPRICE = {type = "NUMERIC", desc = "Расчетная цена"},
        OPTIONTYPE = {type = "STRING", desc = "Тип опциона"},
        OPTIONBASE = {type = "STRING", desc = "Базовый актив"},
        VOLATILITY = {type = "NUMERIC", desc = "Волатильность опциона"},
        THEORPRICE = {type = "NUMERIC", desc = "Теоретическая цена"},
        PERCENTRATE = {type = "NUMERIC", desc = " Агрегированная ставка"},
        ISPERCENT = {type = "STRING", desc = "Тип цены фьючерса"},
        CLSTATE = {type = "STRING", desc = "Статус клиринга"},
        CLPRICE = {type = "NUMERIC", desc = "Котировка последнего клиринга"},
        STARTTIME = {type = "STRING", desc = "Начало основной сессии"},
        ENDTIME = {type = "STRING", desc = "Окончание основной сессии"},
        EVNSTARTTIME = {type = "STRING", desc = "Начало вечерней сессии"},
        EVNENDTIME = {type = "STRING", desc = "Окончание вечерней сессии"},
        MONSTARTTIME = {type = "STRING", desc = "Начало утренней сессии"},
        MONENDTIME = {type = "STRING", desc = "Окончание утренней сессии"},
        CURSTEPPRICE = {type = "STRING", desc = "Валюта шага цены"},
        REALVMPRICE = {type = "NUMERIC", desc = " Текущая рыночная котировка"},
        MARG = {type = "STRING", desc = "Маржируемый"},
        EXPDATE = {type = "NUMERIC", desc = "Дата исполнения инструмента"},
        CROSSRATE = {type = "NUMERIC", desc = "Курс"},
        BASEPRICE = {type = "NUMERIC", desc = "Базовый курс"},
        HIGHVAL = {type = "NUMERIC", desc = "Максимальное значение (RTSIND)"},
        LOWVAL = {type = "NUMERIC", desc = "Минимальное значение (RTSIND)"},
        ICHANGE = {type = "NUMERIC", desc = "Изменение (RTSIND)"},
        IOPEN = {type = "NUMERIC", desc = "Значение на момент открытия (RTSIND)"},
        PCHANGE = {type = "NUMERIC", desc = "Процент изменения (RTSIND)"},
        OPENPERIODPRICE = {type = "NUMERIC", desc = "Цена предторгового периода"},
        MIN_CURR_LAST = {type = "NUMERIC", desc = "Минимальная текущая цена"},
        SETTLECODE = {type = "STRING", desc = "Код расчетов по умолчанию"},
        STEPPRICECL = {type = "DOUBLE", desc = "Стоимость шага цены для клиринга"},
        STEPPRICEPRCL = {type = "DOUBLE", desc = "Стоимость шага цены для промклиринга"},
        MIN_CURR_LAST_TI = {type = "STRING", desc = "Время изменения минимальной текущей цены"},
        PREVLOTSIZE = {type = "DOUBLE", desc = "Предыдущее значение размера лота"},
        LOTSIZECHANGEDAT = {type = "DOUBLE", desc = "Дата последнего изменения размера лота"},
        AUCTPRICE = {type = "NUMERIC", desc = "Цена послеторгового аукциона"},
        CLOSING_AUCTION_VOLUME = {type = "NUMERIC", desc = "Количество в сделках послеторгового аукциона"},
        -------------------------------------
        LONGNAME = {type = "STRING", desc = "Полное название инструмента"},
        SHORTNAME = {type = "STRING", desc = "Краткое название инструмента"},
        CODE = {type = "STRING", desc = "Код инструмента"},
        CLASSNAME = {type = "STRING", desc = "Название класса"},
        CLASS_CODE = {type = "STRING", desc = "Код класса"},
        TRADE_DATE_CODE = {type = "DOUBLE", desc = "Дата торгов"},
        MAT_DATE = {type = "DOUBLE", desc = "Дата погашения"},
        DAYS_TO_MAT_DATE = {type = "DOUBLE", desc = "Число дней до погашения"},
        SEC_FACE_VALUE = {type = "DOUBLE", desc = "Номинал инструмента"},
        SEC_FACE_UNIT = {type = "STRING", desc = "Валюта номинала"},
        SEC_SCALE = {type = "DOUBLE", desc = "Точность цены"},
        SEC_PRICE_STEP = {type = "DOUBLE", desc = "Минимальный шаг цены"},
        SECTYPE = {type = "STRING", desc = "Тип инструмента"},
    }
end

return roffild_win1251
